/**
 * Task representation using git-backed storage
 * Inspired by Gastown's Beads system
 */
export interface Task {
  id: string; // Format: cs-xxxxx (5 alphanumeric chars)
  title: string;
  description: string;
  status: TaskStatus;
  assignedAgent?: string;
  createdAt: Date;
  updatedAt: Date;
  priority: TaskPriority;
  tags: string[];
}

export enum TaskStatus {
  OPEN = 'open',
  IN_PROGRESS = 'in_progress',
  COMPLETED = 'completed',
  BLOCKED = 'blocked'
}

export enum TaskPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical'
}

/**
 * Agent representation - first-class citizens
 */
export interface Agent {
  id: string;
  name: string;
  status: AgentStatus;
  currentTask?: string; // Task ID
  terminalPid?: number;
  runtime?: AgentRuntime;
  flyAppName?: string;
  mailbox: Message[];
  capabilities: string[];
  createdAt: Date;
}

export enum AgentRuntime {
  LOCAL = 'local',
  FLY = 'fly'
}

export enum AgentStatus {
  IDLE = 'idle',
  WORKING = 'working',
  OFFLINE = 'offline',
  ERROR = 'error'
}

/**
 * Message for agent communication
 */
export interface Message {
  id: string;
  from: string; // 'system' or agent ID
  to: string; // agent ID
  subject: string;
  body: string;
  timestamp: Date;
  read: boolean;
}

/**
 * Convoy - group of related tasks
 */
export interface Convoy {
  id: string;
  name: string;
  description: string;
  tasks: string[]; // Task IDs
  createdAt: Date;
  status: ConvoyStatus;
}

export enum ConvoyStatus {
  ACTIVE = 'active',
  COMPLETED = 'completed',
  PAUSED = 'paused'
}

/**
 * Workspace configuration
 */
export interface WorkspaceConfig {
  name: string;
  path: string;
  repository?: string;
  agents: Agent[];
  oauthConfig?: OAuthConfig;
}

/**
 * OAuth configuration for coding plan
 */
export interface OAuthConfig {
  clientId?: string;
  tokenPath?: string;
  scopes: string[];
}

/**
 * Work plan generated by Prometheus
 * Stored as markdown in .createsuite/plans/
 */
export interface Plan {
  name: string;
  path: string;
  content: string;
  tasks: PlanTask[];
  createdAt: Date;
  modifiedAt: Date;
}

/**
 * Task parsed from plan markdown checkboxes
 */
export interface PlanTask {
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  lineNumber: number;
}

/**
 * Repository configuration for agent work
 */
export interface RepoConfig {
  url: string;           // GitHub URL (https://github.com/owner/repo)
  owner: string;
  name: string;
  localPath: string;     // Where the repo is cloned locally
  defaultBranch: string; // main, master, etc.
  clonedAt: Date;
}

/**
 * Skill category from agent-skills.json
 */
export interface SkillCategory {
  name: string;
  skills: string[];
  direction: string;
}

/**
 * Router result from SmartRouter
 */
export interface RouterResult {
  recommended: WorkflowType;
  confidence: number;
  reasoning: string;
  suggestedSkills: string[];
  estimatedAgents: number;
}

export type WorkflowType = 'simple' | 'complex' | 'team';

/**
 * Pipeline configuration for a full CreateSuite run
 */
export interface PipelineConfig {
  repoUrl: string;
  goal: string;
  provider?: string;
  model?: string;
  githubToken?: string;
  maxAgents?: number;
  dryRun?: boolean;
}

/**
 * Pipeline status for tracking end-to-end runs
 */
export interface PipelineStatus {
  id: string;
  repoUrl: string;
  goal: string;
  phase: PipelinePhase;
  convoyId?: string;
  prUrl?: string;
  startedAt: Date;
  completedAt?: Date;
  error?: string;
}

export enum PipelinePhase {
  CLONING = 'cloning',
  PLANNING = 'planning',
  EXECUTING = 'executing',
  COMMITTING = 'committing',
  PR_CREATING = 'pr_creating',
  COMPLETED = 'completed',
  FAILED = 'failed'
}
